{% set name = "effectsize" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/effectsize-{{ version }}.tar.gz
  sha256: 2022a0abdd2429c5ee4ebb679d4b1c35031b2510846b4f05faf6e1dba4a1b62b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7
    - scipy
    - statsmodels

test:
  imports:
    - effectsize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nbashir97/effectsize
  summary: A Python package for computing effect sizes
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - nbashir97
