{% set name = "effectsize" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/effectsize-{{ version }}.tar.gz
  sha256: 2f5a67f436b57437cfb3aa8885804811bf50b9f055f135560d4ed74ed131ac03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7
    - scipy
    - statsmodels

test:
  imports:
    - effectsize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nbashir97/effectsize
  summary: A Python package for computing effect sizes
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - nbashir97
